# Generated by Django 5.2.1 on 2025-05-12 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['created_at'], 'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Quote', 'verbose_name_plural': 'Quotes'},
        ),
        migrations.AlterModelOptions(
            name='rfq',
            options={'ordering': ['-created_at'], 'verbose_name': 'Request For Quotation', 'verbose_name_plural': 'Requests For Quotations'},
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_failed', 'Payment Failed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled_by_buyer', 'Cancelled by Buyer'), ('cancelled_by_seller', 'Cancelled by Seller'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='pending_payment', max_length=30),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quantity_offered',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='specifications_file',
            field=models.FileField(blank=True, null=True, upload_to='rfqs/specifications/%Y/%m/%d/'),
        ),
    ]
