# Generated by Django 5.2.1 on 2025-05-08 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated styles, themes (e.g., floral, abstract, modern)', max_length=255)),
                ('design_image', models.ImageField(blank=True, null=True, upload_to='designs_images/')),
                ('customization_preferences', models.TextField(blank=True, help_text='e.g., Colors can be changed, open to size variations.')),
                ('licensing_options', models.CharField(choices=[('EXCLUSIVE', 'Exclusive'), ('NON_EXCLUSIVE', 'Non-Exclusive'), ('ROYALTY', 'Royalty-based')], default='EXCLUSIVE', max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='One-time purchase price or license fee base.', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('fabric_type', models.CharField(choices=[('COTTON', 'Cotton'), ('SILK', 'Silk'), ('WOOL', 'Wool'), ('LINEN', 'Linen'), ('POLYESTER', 'Polyester'), ('RAYON', 'Rayon'), ('DENIM', 'Denim'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('quantity_available', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measurement', models.CharField(default='meters', max_length=20)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('region_available', models.CharField(blank=True, max_length=100)),
                ('certifications', models.CharField(blank=True, help_text='e.g., GOTS, Oeko-Tex, comma-separated', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_listed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
