# Generated by Django 5.2.1 on 2025-05-09 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('issuing_body', models.CharField(max_length=200)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certifications/')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='design',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='design',
            name='customization_preferences',
        ),
        migrations.RemoveField(
            model_name='design',
            name='design_image',
        ),
        migrations.RemoveField(
            model_name='design',
            name='licensing_options',
        ),
        migrations.RemoveField(
            model_name='material',
            name='fabric_type',
        ),
        migrations.RemoveField(
            model_name='material',
            name='image',
        ),
        migrations.RemoveField(
            model_name='material',
            name='min_order_quantity',
        ),
        migrations.RemoveField(
            model_name='material',
            name='quantity_available',
        ),
        migrations.RemoveField(
            model_name='material',
            name='region_available',
        ),
        migrations.RemoveField(
            model_name='material',
            name='unit_of_measurement',
        ),
        migrations.AddField(
            model_name='design',
            name='design_files_link',
            field=models.URLField(blank=True, help_text='Link to secure storage for design files (e.g., for after purchase)', null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='design',
            name='licensing_terms',
            field=models.TextField(blank=True, help_text='Details about licensing, e.g., exclusive, non-exclusive, usage rights.', null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/%(class)s_main_images/'),
        ),
        migrations.AddField(
            model_name='design',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=270, unique=True),
        ),
        migrations.AddField(
            model_name='design',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='designs/thumbnails/'),
        ),
        migrations.AddField(
            model_name='material',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='composition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='lead_time_days',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated lead time in days for production/sourcing if not in stock.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/%(class)s_main_images/'),
        ),
        migrations.AddField(
            model_name='material',
            name='minimum_order_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='material',
            name='review_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='material',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=270, unique=True),
        ),
        migrations.AddField(
            model_name='material',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('m', 'Meter'), ('kg', 'Kilogram'), ('sqm', 'Square Meter'), ('pcs', 'Pieces'), ('yard', 'Yard'), ('lb', 'Pound')], default='m', max_length=10),
        ),
        migrations.AddField(
            model_name='material',
            name='weight_gsm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='width_cm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='design',
            name='designer',
            field=models.ForeignKey(limit_choices_to={'user_type__in': ['designer']}, on_delete=django.db.models.deletion.CASCADE, related_name='designs_listed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='design',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for the design or license.', max_digits=10, null=True),
        ),
        migrations.RemoveField(
            model_name='design',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='material',
            name='certifications',
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='seller',
            field=models.ForeignKey(limit_choices_to={'user_type__in': ['seller', 'manufacturer']}, on_delete=django.db.models.deletion.CASCADE, related_name='materials_listed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='listings.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='design',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_listings', to='listings.category'),
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_listings', to='listings.category'),
        ),
        migrations.AddField(
            model_name='design',
            name='certifications',
            field=models.ManyToManyField(blank=True, to='listings.certification'),
        ),
        migrations.AddField(
            model_name='material',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_listings', to='listings.tag'),
        ),
        migrations.CreateModel(
            name='TechPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='designs/tech_packs/')),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_packs', to='listings.design')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='design',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_listings', to='listings.tag'),
        ),
        migrations.AddField(
            model_name='material',
            name='certifications',
            field=models.ManyToManyField(blank=True, to='listings.certification'),
        ),
    ]
