# Generated by Django 5.2 on 2025-05-10 09:55

import apps.listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_certification_tag_alter_design_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techpack',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='design',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='review_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.listings.models.get_certification_file_upload_path),
        ),
        migrations.AlterField(
            model_name='design',
            name='design_files_link',
            field=models.URLField(blank=True, help_text='Link to secure storage for design files...', null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='licensing_terms',
            field=models.TextField(blank=True, help_text='Details about licensing...', null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.listings.models.get_listing_image_upload_path),
        ),
        migrations.AlterField(
            model_name='design',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.listings.models.get_design_thumbnail_upload_path),
        ),
        migrations.AlterField(
            model_name='material',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.listings.models.get_listing_image_upload_path),
        ),
        migrations.AlterField(
            model_name='techpack',
            name='file',
            field=models.FileField(upload_to=apps.listings.models.get_tech_pack_upload_path),
        ),
    ]
